### PR TITLE
test type associated columns not null

### PR DESCRIPTION
**Pull request by lrnzcig**
Fixes [4](https://github.com/datakind/Data-Observation-Toolkit/issues/4) for associated_columns_not_null -the issue itself was closed, but the test type associated columns not null did not have a test

note that the test was broken - look at the changes to the macro [test_associated_columns_not_null](dot/dbt/macros/test_associated_columns_not_null.sql)

### CODE REVIEW

**Comment by lrnzcig** [comment]
@JanPeterDatakind @dividor apologies I left this pending for such a long time
ready to review now

**Comment by JanPeterDatakind** [comment]
Hi Lorenzo, 

I just checked out that version of DOT and ran it locally: Running DOT works fine and in the DB, everything looks fine too as far as I can tell. On the test page in Appsmith however, I get an error that "the action 'configured_tests_data' has failed" and the table that should show the configured tests is empty. The corresponding query that fails seems to be this one: 
SELECT 
  ct.*,
  ce.entity_id,
	dot.test_params_all_json()::jsonb
FROM 
  dot."configured_tests" ct,
  dot."configured_entities" ce
where 
  ce.entity_id = ct.entity_id
AND "description" ilike '%{{configured_tests.searchText || ""}}%'
ORDER BY "{{col_select.selectedOptionValue}}" {{order_select.selectedOptionValue}}
LIMIT {{configured_tests.pageSize}}
OFFSET {{(configured_tests.pageNo - 1) * configured_tests.pageSize}};

Weirdly enough, other stuff such as projects/entity_categories/entities are shown correctly, I can create new tests through the UI and they're saved to the DB as expected. Do you know if that failing SQL query could have something to do with the changes in this PR?

**Comment by lrnzcig** [comment]
@JanPeterDatakind indeed it was the change in the new column in `test_parameters_interface` that made the function `test_params_all_json` fail... I should maybe add a test for the function, so that we don't break it again

**Comment by lrnzcig** [comment]
@JanPeterDatakind the commit just above adds a test for `test_params_all_json` so that hopefully we don't break it again

**Pull request merged**
