### PR TITLE
add self test for test type possible_duplicate_forms

### PR DESCRIPTION
**Pull request by lrnzcig**
@dividor when working on test type "possible_duplicate_forms" to add it to the self_tests, I've realised what I believe is a bug, but I'm very surprised we did not find it before

I'd appreciate your inputs in these questions:
- what did you have in mind with this [comment](https://github.com/datakind/Data-Observation-Toolkit/blob/c528d47fb99271e4817c843fdde63cfc19c59dd7/db/dot/4-upload_sample_dot_data.sql#L62), if you remember?
- is it by any chance possible that we are not using any of these test types in Muso: "possible_duplicate_forms", "associated_columns_not_null", "relationships", "not_negative_string_column"? -these are the ones using `uuid_list` in their dbt macros, and thus they are affected by the bug, thus if we are using any of these we would see an impact

I would be happy if you prove that I'm making a silly mistake somewhere, but just don't see it!
thx

### CODE REVIEW

**Comment by lrnzcig** [comment]
note that the tests are failing since this affects the test totals (number of rows that have failed) and the failed rows themselves

**Comment by dividor** [comment]
Hi @lrnzcig,

- "what did you have in mind with this [comment](https://github.com/datakind/Data-Observation-Toolkit/blob/c528d47fb99271e4817c843fdde63cfc19c59dd7/db/dot/4-upload_sample_dot_data.sql#L62), if you remember?"

The name 'duplicate_forms' is specific to the use-case as not all data DOT will be used with relates to forms, I think we could rename this to something like 'duplicate_followup_record' or something.

- "is it by any chance possible that we are not using any of these test types in Muso: "possible_duplicate_forms", "associated_columns_not_null", "relationships", "not_negative_string_column"? -these are the ones using uuid_list in their dbt macros, and thus they are affected by the bug, thus if we are using any of these we would see an impact"

Very possibly, I commented out some test types as part of hitting the submission for global digital goods. If the bug fix resolves this, then great.

Note that the bug may have been introduced as part of the refactor for open source perhaps, though we did ensure self-tests were passing so that seems a bit odd.

Thanks!

**Comment by lrnzcig** [comment]
thanks @dividor 

no, the self tests did not cover this

(always knew that our test coverage was not so great, but you don't expect such a bug to come through!)

the test that is failing now is a new one I added in my last PR...

I don't see any other explanation that the bug being there all along... but there is a very clear symptom (in `all_tests_sumary.xlsx` the column `rows_total` is not equal to `rows_failed` + `rows_passed`, that's why I noticed), which does not happen in the last execution I've got in my laptop from `Data-Observation-Toolkit.legacy`

I'll investigate on that and try to get to the bottom, this is a bit suspicious

**Comment by dividor** [comment]
Thanks for spotting and looking into it

**Comment by lrnzcig** [comment]
finally got the problem, it is [here](https://github.com/datakind/Data-Observation-Toolkit/blob/994ba4d0e9f05a018252eddeee6a48eaa6d89152/db/dot/3-demo_data.sql#L3)
in Muso we defined the uuid fields as `text`, and here as `UUID`

the object that postgres gives back in either case is different

in this PR I'll make it work in either of the 2 cases

**Comment by dividor** [comment]
Thanks so much Lorenzo!

**Comment by lrnzcig** [comment]
done @dividor!

**Review by dividor — APPROVED** [review]
As always, great stuff, thanks!

**Pull request merged**
